### ISSUE TITLE
The number images of mimic dataset

### ISSUE THREAD

**Issue by donghaozhang** [cuhksz-nlp/R2Gen#1]
train_image_num 270790 val_image_num 2130 test_image_num 3858

Dear Zhihong,

Your code is nice and clean. Thank you so much! Based on the json file you provided, I can only find around 270000 images which is different from table 1 in your paper. The able has around 360000 images. Do you have any selection criteria?

Kind Regards,
Donghao

**Comment by zhjohnchan** [comment]
@donghaozhang Thanks for your interest. Table 1 shows the statistics of the datasets stated in the original papers.

**Comment by zhjohnchan** [comment]
Hello,

**Comment by zhjohnchan** [comment]
Dear Donghao,

Thanks for your interest.
Table 1 shows the statistics of the datasets stated in the original papers. Some images have no corresponding reports and thus I do not include them in the json file.

Best,
Zhihong
