### ISSUE TITLE
AssertionError on MIMIC-CXR dataset

### ISSUE THREAD

**Issue by WANGCHENYU123** [cuhksz-nlp/R2Gen#15]
I am training the model on MIMIC-CXR dataset, but the training is always stop at epoch 11 and an AssertionError occurs. The attached file is the screenshot of the error. Thank you very much.
<img width="1249" alt="Screenshot 2021-09-14 at 19 51 21" src="https://user-images.githubusercontent.com/28296613/133806975-65a682d1-8386-4330-baa2-44812b0f80b6.png">

**Comment by munanning** [comment]
I found a possible solution. Just update your Torch to 1.7.1

**Comment by zhjohnchan** [comment]
@munanning Thanks for your solution. Updating the PyTorch version is exactly the way to solve this problem.

**Comment by JiuZhouu** [comment]
hi there, could you pls share me the MIMIC dataset? thank you a lotTTTTTTTT!!!!!

**Comment by munanning** [comment]
链接：https://pan.baidu.com/s/1SbX3RfmKx1ejc9JlsuXekQ?pwd=6h9t&nbsp;
提取码：6h9t&nbsp;
--来自百度网盘超级会员V4的分享

30 days available

**Comment by JiuZhouu** [comment]
Thank you！！！
Really helps me.


Wish you a good day


Yuxing&nbsp;Zhao
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "cuhksz-nlp/R2Gen"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Jul 10, 2023 03:50 PM
***@***.***&gt;;
Cc:&nbsp;"Yuxing ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [cuhksz-nlp/R2Gen] AssertionError on MIMIC-CXR dataset (#15)





 链接：https://pan.baidu.com/s/1SbX3RfmKx1ejc9JlsuXekQ?pwd=6h9t&amp;nbsp; 
 提取码：6h9t&amp;nbsp; 
 --来自百度网盘超级会员V4的分享 
 
 here 
 no share to others 
 
 &amp;nbsp; 
 
 
 宁慕楠 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "yuxing ***@***.***&amp;gt;;  
 发送时间: 2023年7月10日(星期一) 下午3:19 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [cuhksz-nlp/R2Gen] AssertionError on MIMIC-CXR dataset (#15) 
 
 
 
 
 
   
 hi there, could you pls share me the MIMIC dataset? thank you a lotTTTTTTTT!!!!!

**Comment by deng1604** [comment]
> 链接：https://pan.baidu.com/s/1SbX3RfmKx1ejc9JlsuXekQ?pwd=6h9t&nbsp; 提取码：6h9t&nbsp; --来自百度网盘超级会员V4的分享 可用 30 天

你好，我想问下，跑这个MIMIC-CXR 数据集，真的有500多GB吗？ 
这对我来说太大了💔

**Comment by deng1604** [comment]
> 链接：https://pan.baidu.com/s/1SbX3RfmKx1ejc9JlsuXekQ?pwd=6h9t&nbsp; 提取码：6h9t&nbsp; --来自百度网盘超级会员V4的分享 可用 30 天

您好，可以发我下这个MIMIC数据集吗，非常感激！

**Comment by Hhhhao594188** [comment]
> hi there, could you pls share me the MIMIC dataset? thank you a lotTTTTTTTT!!!!!

Hello, I need mimic this data set. Could you please send me a copy? Thank you very much. My email is hao18825911671@foxmail.com

**Comment by lmh123-zxg** [comment]
> 谢谢！！！真的帮了我大忙。祝你今天过得愉快！赵宇星 ***@***.***
> […](#)

您好MIMIC数据集可以分享下吗？我的邮箱是lmh2668@163.com
