### ISSUE TITLE
Datasets did not contain all the data

### ISSUE THREAD

**Issue by windstormer** [cuhksz-nlp/R2Gen#16]
Hi,
According to your paper, the IU X-Ray dataset contains 5226, 748, and 1496 images on train, val, and test, respectively.
However, the provided dataset you had published contains only 2069, 296, and 590 images, written in the annotation.json.
Is the shared dataset you used for training and testing?
If not, could you share your splitted dataset to me?
MIMIC-CXR dataset also had a similar problem, with 270790, 2130, and 3858, for the splitted dataset, which did not match the number present in your paper.

![image](https://user-images.githubusercontent.com/14368570/136334002-22e2e475-aaf2-41b6-ad8f-6f116f3ea49d.png)

**Comment by tangyuxing** [comment]
Hi,

The number of images in the json file is indeed inconsistent with Table 1 of the paper. 

In the json file, [2069, 296, 590] are the number of studies, while each study has one or multiple (normal 2: frontal and lateral view) x-ray images. The number of images in the json file is 5910 in total.

**Comment by zhjohnchan** [comment]
Dear @tangyuxing and @windstormer,

Thanks for your attention to our paper! The statistics shown in the Table are from their original paper and the data provided is the pre-preprocessed one.

Best,
Zhihong
