### ISSUE TITLE
关于COATT的引用

### ISSUE THREAD

**Issue by qigeshige** [cuhksz-nlp/R2Gen#17]
您好，我想问一下，为什么COATT模型原论文中的效果BLEU-1为0.517，但是R2Gen和CMN论文中引用的是0.455

**Comment by zhjohnchan** [comment]
@qigeshige 您好，COATT的分数在该组后续的文章（例如，hybrid retrieval-generation reinforced agent for medical image report generation）被更新过，原因是使用了新的设置，不使用Impression。
