### ISSUE TITLE
Do not have datasets access

### ISSUE THREAD

**Issue by jessie-chen99** [cuhksz-nlp/R2Gen#34]
![image](https://user-images.githubusercontent.com/62527700/227202061-d779526c-4cdf-4a83-81be-a80342953487.png)

looking forward for your reply! thanks a lot!

https://drive.google.com/file/d/1DS6NYirOXQf8qYieSVMvqNwuOlgAbM_E/view?usp=sharing

**Comment by JiuZhouu** [comment]
hi do you got the reply or the dataset? meeting with the same problem, wish to get your help

**Comment by deng1604** [comment]
> 嗨，你得到回复或数据集了吗？遇到同样的问题，希望得到您的帮助

你好，请问你现在有这个数据集了吗？

**Comment by Hhhhao594188** [comment]
> > 嗨，你得到回复或数据集了吗？遇到同样的问题，希望得到您的帮助
> 
> 你好，请问你现在有这个数据集了吗？

你好，请问你现在有mimic这个数据集了吗
