### ISSUE TITLE
BASE Model

### ISSUE THREAD

**Issue by nooralahzadeh** [cuhksz-nlp/R2Gen#4]
Hi,
Thanks for sharing the code. Your approach is very interesting.
I wonder how I can run the code in baseline mode (Base Model in Table 2).
Thanks in avdance!

**Comment by nooralahzadeh** [comment]
I just replace the conditional layer with the normal layer and ignore the rm.

**Comment by jainnipun11** [comment]
Hey, @nooralahzadeh if it's possible, could you please share the code?

Thanks,
Nipun Jain
