### ISSUE TITLE
Optimum epoch number to reproduce your result? 

### ISSUE THREAD

**Issue by nooralahzadeh** [cuhksz-nlp/R2Gen#5]
Hi,
Could you please share in which epoch you save the checkpoints?

Best,

**Comment by zhjohnchan** [comment]
Dear @nooralahzadeh,

Thanks for your attention to our paper. We save the checkpoints according to the performance on the validation set and you can refer to `modules/trainer.py`. PLUS, the `IU X-Ray` dataset is small, so the variance of the results may be larger.

Best,
Zhihong
