### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by nooralahzadeh** [cuhksz-nlp/R2Gen#6]
Hi, 
Could you please share the number that you used for the random seed to generate the results for 5 runs in your experiments on IU-XRAY and MIMIC?
Thanks

**Comment by zhjohnchan** [comment]
Dear Farhad,

For IU X-Ray, the seeds are 9223, 3247671, 98726412, 12415108, 1248912.

For MIMIC-CXR, the seeds are 456789, 123, 45678, 134345, 974357.

Best,
Zhihong
